import Wesanb from '../iamge/sheet1/wesanb.png';
import Radwan from '../iamge/sheet1/radwan.png';
import Madaa from '../iamge/sheet1/madaa.png';
import Msireg from '../iamge/sheet1/msireg.png';
import Oad from '../iamge/sheet1/oad.png';
import Rada from '../iamge/sheet1/rada.png';
import Reeima from '../iamge/sheet1/reeima.png';
import Hswa from '../iamge/sheet1/hswa.png';
import Bhwan from '../iamge/sheet1/bhwan.png';
import Reem from '../iamge/sheet1/reem.png';
import Sharf from '../iamge/sheet1/sharf.png';
import Roam from '../iamge/sheet1/roam.png';
import Soda from '../iamge/sheet1/soda.png';
import Tib from '../iamge/sheet1/tib.png';
import Btna from '../iamge/sheet1/btna.png';
import Thoaba from '../iamge/sheet1/thoaba.png'
import Khdar from '../iamge/sheet1/khdar.png'
import marba from '../iamge/sheet1/marba.png'
import ashran from '../iamge/sheet1/ashran.png'
import tndha from '../iamge/sheet1/tndha.png'
import almaawen from '../iamge/sheet1/almaawen.png'
import atheb from '../iamge/sheet1/atheb.png'
import alaina from '../iamge/sheet1/alaina.png'
import abha from '../iamge/sheet1/abha.png'
import atodkhamis from '../iamge/sheet1/atodkhamis.png'
import hgla from '../iamge/sheet1/hgla.png'
import thmania from '../iamge/sheet1/thmania.png'
import althfn from '../iamge/sheet1/althfn.png'
import sbh from '../iamge/sheet1/sbh.png'
import agda from '../iamge/sheet1/38da.png'
import wstmrma from '../iamge/sheet1/wstmrma.png'
import atodg from '../iamge/sheet1/atodg.png'
import aodgof from '../iamge/sheet1/aodgof.png'
import al3sm from '../iamge/sheet1/al3sm.png'
import thll from '../iamge/sheet1/thll.png'

import alamal from '../iamge/sheet2/alamal.png'
import almshreb from '../iamge/sheet2/almshreb.png'
import alramid from '../iamge/sheet2/alramid.png'
import arara from '../iamge/sheet2/arara.png'
import bsam from '../iamge/sheet2/bsam.png'
import griha from '../iamge/sheet2/griha.png'
import khader from '../iamge/sheet2/khader.png'
import wgier from '../iamge/sheet2/wgier.png'
import zhra from '../iamge/sheet2/zhra.png'
import derham from '../iamge/sheet2/derham.png'
import gbda from '../iamge/sheet2/gbda.png'
import hrga from '../iamge/sheet2/hrga.png'
import fgais from '../iamge/sheet2/fgais.png'
import nhra from '../iamge/sheet2/nhra.png'
import hdila from '../iamge/sheet2/hdila.png'
import mrga from '../iamge/sheet2/mrga.png'
import smakia from '../iamge/sheet2/smakia.png'
// import  from '../iamge/sheet2/.png'
import gaeel from '../iamge/sheet2/gaeel.png'
import fitlha from '../iamge/sheet2/fitlha.png'
import shergeb from '../iamge/sheet2/shergeb.png'
import shrom from '../iamge/sheet2/shrom.png'
import normal from '../iamge/sheet2/normal.png'
import hjrzher from '../iamge/sheet2/hjrzher.png'
import gofmamer from '../iamge/sheet2/gofmamer.png'
import rshed from '../iamge/sheet2/rshed.png'
import ananm from '../iamge/sheet2/ananm.png'
import hgla1 from '../iamge/sheet2/hgla.png'

import araer from '../iamge/sheet2/araer.png'
import feed from '../iamge/sheet2/feed.png'
import ktam from '../iamge/sheet2/ktam.png'

import froon from '../iamge/sheet2/froon.png'
import shabhrja from '../iamge/sheet2/shabhrja.png'
import frdan from '../iamge/sheet2/frdan.png'
import saroi from '../iamge/sheet2/saroi.png'
import osran from '../iamge/sheet2/osran.png'

import algoha from '../iamge/sheet2/algoha.png'
import alaiza from '../iamge/sheet2/alaiza.png'
import mohzam from '../iamge/sheet2/mohzam.png'
import wadidaf from '../iamge/sheet2/wadidaf.png'
import farha from '../iamge/sheet2/farha.png'
import abugadaa from '../iamge/sheet2/abugadaa.png'







const Sade = [
   
    {
      "north": "18.280217",
      "east": "42.33365",
      "date": "1406",
      "Sirens": 1,
      "Portals": 1,
      "valves": 0,
      "Lighting": 0,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 35000,
      "high": 9,
      "length": 12,
      "type": "خرساني",
      "purpose": "حماية",
      "d_name": "العوص",
      "governorate": "رجال المع",
      "id": "1",
      "photo":Oad,
      "spillyway_h": 55,
    },

    {
      "north":"18.235867",
      "east":"42.178497",
      "date": "1403هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 50000,
      "high": 8,
      "length": 11,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ريم",
      "governorate": "رجال المع",
      "id": "2",
      "photo":Reem,
      "spillyway_h": 55,
    },

    {
      "north": "18.29138",
      "east": "42.444115",
      "date": "1404هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 60000,
      "high": 12,
      "length": 15,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ال عاصم",
      "governorate": "أبها",
      "id": "3",
      "photo": al3sm,
      "spillyway_h": 70,
    },
    {
      "north": "18.236389",
      "east": "42.412778",
      "date": "1404هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 340000,
      "high": 10,
      "length": 13,
      "type": "خرساني",
      "purpose": "حماية",
      "d_name": "السوده(المقضى)",
      "governorate": "أبها",
      "id": "4",
      "photo": Soda,
      "spillyway_h": 28,
    },
    {
      "north": "18.266239",
      "east": "42.270122",
      "date": "1404",
      "Sirens": 1,
      "Portals": 0,
      "valves": 1,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 230000,
      "high": 8,
      "length": 11,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ثعابه",
      "governorate": "رجال المع",
      "id": "6",
      "photo":Thoaba,
      "spillyway_h": 100,
    },
    {
      "north": "18.858056",
      "east": "42.655278",
      "date": "1404",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 151800,
      "high": 10,
      "length": 13,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "البطنه",
      "governorate": "خميس مشيط",
      "id": "7",
      "photo":Btna,
      "spillyway_h": 360,
    },
    {
      "north": "18.329722",
      "east": "42.0925",
      "date": "1406",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 1500000,
      "high": 13,
      "length": 16,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "روام",
      "governorate": "رجال المع",
      "id": "8",
      "photo":Roam,
      "spillyway_h": 57,
    },
    {
      "north": "18.355",
      "east": "42.386389",
      "date": "1431هـ",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 230000,
      "high": 12,
      "length": 15,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ريمه",
      "governorate": "أبها",
      "id": "9",
      "photo":Reeima,
      "spillyway_h": 205,
    },
    {
      "north": "18.447222",
      "east": "43.371389",
      "date": "1432هـ",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 0,
      "Guard": 0,
      "management": 1,
      "i_security": 1,
      "capacity": 355650,
      "high": 6,
      "length": 8,
      "type": "ترابي",
      "purpose": "استعاضة",
      "d_name": "طليحة الشرف",
      "governorate": "ابها",
      "id": "10",
      "photo":Sharf,
      "spillyway_h": 281,
    },
      {
        "north": "18.358056",
        "east": "42.240833",
        "date": "1406",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 182000,
        "high": 20,
        "length": 23,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "وسانب",
        "governorate": "رجال المع",
        "id": "12",
        "photo": Wesanb,
        "spillyway_h": 100,
      },
      {
        "north": "18.236714",
        "east": "42.205464",
        "date": "1406",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 192000,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "راده",
        "governorate": "رجال المع",
        "id": "13",
        "photo": Rada,
        "spillyway_h": 70,
      },
      {
        "north": "18.053333",
        "east": "42.2683",
        "date": "1403هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 300000,
        "high": 5.5,
        "length": 8,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "العاينه",
        "governorate": "رجال المع",
        "id": "14",
        "photo": alaina,
        "spillyway_h": 80,
      },
      {
        "north": "18.578056",
        "east": "42.818056",
        "date": "1437",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 357160,
        "high": 4,
        "length": 6.5,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "روضان",
        "governorate": "خميس مشيط",
        "id": "15",
        "photo": Radwan,
        "spillyway_h": 169,
      },
      {
        "north": "18.263611",
        "east": "43.601389",
        "date": "1417هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 500000,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "جوفي",
        "d_name": "وسط مرمى",
        "governorate": "خميس مشيط",
        "id": "16",
        "photo": wstmrma,
        "spillyway_h": 85,
      },
      {
        "north": "18.295806",
        "east": "42.654453",
        "date": "1398هـ",
        "Sirens": 0,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 1000000,
        "high": 8,
        "length": 12,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "حجلا",
        "governorate": "أبها",
        "id": "17",
        "photo": hgla,
        "spillyway_h": 180,
      },
      {
        "north": "18.6825",
        "east": "42.413611",
        "date": "1432هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 121560,
        "high": 8,
        "length": 11,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "بهوان",
        "governorate": "أبها",
        "id": "18",
        "photo": Bhwan,
        "spillyway_h": 275,
      },
      {
        "north": "18.367438",
        "east": "42.361866",
        "date": "1403هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 90000,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "طبب",
        "governorate": "أبها",
        "id": "19",
        "photo": Tib,
        "spillyway_h": 50,
      },
      {
        "north": "19.049444",
        "east": "42.908611",
        "date": "1430هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 433000,
        "high": 6,
        "length": 9,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "المسيرق",
        "governorate": "خميس مشيط",
        "id": "20",
        "photo": Msireg,
        "spillyway_h": 84,
      },
      {
        "north": "18.787722",
        "east": "43.210619",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 4250000,
        "high": 6.5,
        "length": 8,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "المضه",
        "governorate": "خميس مشيط",
        "id": "21",
        "photo": Madaa,
        "spillyway_h": 1070,
      },
   
      {
        "north": "18.204321",
        "east": "42.31512",
        "date": "1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 200000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "حسوه",
        "governorate": "رجال المع",
        "id": "23",
        "photo": Hswa,
        "spillyway_h": 45,
      },
      {
        "north": "18.677844",
        "east": "42.331407",
        "date": "1432هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 229700,
        "high": 10,
        "length": 13,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "صبح",
        "governorate": "أبها",
        "id": "24",
        "photo": sbh,
        "spillyway_h": 130,
      },
      {
        "north": "18.023",
        "east": "42.7637",
        "date": "1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 300000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "تمنية",
        "governorate": "أبها",
        "id": "25",
        "photo": thmania,
        "spillyway_h": 100,
      },
      {
        "north": "18.650156",
        "east": "42.397278",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 400000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الماوين",
        "governorate": "أبها",
        "id": "26",
        "photo": almaawen,
        "spillyway_h": 120,
      },
      {
        "north": "18.269167",
        "east": "42.438056",
        "date": "1404",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 1500000,
        "high": 31.5,
        "length": 38,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "عشران",
        "governorate": "أبها",
        "id": "27",
        "photo": ashran,
        "spillyway_h": 111,
      },
      {
        "north": "18.850858",
        "east": "42.855842",
        "date": "1405هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 1064000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "اثب",
        "governorate": "خميس مشيط",
        "id": "28",
        "photo": atheb,
        "spillyway_h": 95,
      },
      {
        "north": "18.695833",
        "east": "42.527222",
        "date": "1431هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 1128733,
        "high": 6,
        "length": 9,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "خضار الحيمة",
        "governorate": "خميس مشيط",
        "id": "29",
        "photo": Khdar,
        "spillyway_h": 648,
      },
      {
        "north": "18.403611",
        "east": "42.4",
        "date": "1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 140000,
        "high": 10.5,
        "length": 13.5,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "تهلل",
        "governorate": "أبها",
        "id": "30",
        "photo": thll,
        "spillyway_h": 140,
      },
      {
        "north": "18.209935",
        "east": "42.488654",
        "date": "1394هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 0,
        "i_security": 1,
        "capacity": 2130000,
        "high": 22.5,
        "length": 25.5,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "أبها",
        "governorate": "أبها",
        "id": "31",
        "photo": abha,
        "spillyway_h": 350,
      },
      {
        "north": "18.312683",
        "east": "42.876847",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 0,
        "capacity": 4200000,
        "high": 10,
        "length": 16,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "تندحه",
        "governorate": "خميس مشيط",
        "id": "32",
        "photo": tndha,
        "spillyway_h": 120,
      },
      {
        "north": "18.260411",
        "east": "42.715894",
        "date": "1402هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 0,
        "i_security": 1,
        "capacity": 6240000,
        "high": 16,
        "length": 22,
        "type": "ركامي",
        "purpose": "للشرب",
        "d_name": "عتود",
        "governorate": "خميس مشيط",
        "id": "33",
        "photo": atodkhamis,
        "spillyway_h": 340,
      },
      {
        "north": "17.850739",
        "east": "42.386114",
        "date": "1428هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 7000000,
        "high": 0,
        "length": 28,
        "type": "جوفي",
        "purpose": "للشرب",
        "d_name": "عتود الجوفي",
        "governorate": "أبها",
        "id": "34",
        "photo": aodgof,
        "spillyway_h": 456,
      },
      {
        "north": "17.903333",
        "east": "42.384722",
        "date": "1429",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 10000000,
        "high": 26,
        "length": 32,
        "type": "ترابي",
        "purpose": "للشرب",
        "d_name": "مربة",
        "governorate": "مربة",
        "id": "35",
        "photo": marba,
        "spillyway_h": 215,
      },
      {
        "north": "17.900556",
        "east": "42.471111",
        "date": "1429",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 10000000,
        "high": 29,
        "length": 35,
        "type": "ترابي",
        "purpose": "للشرب",
        "d_name": "عتود",
        "governorate": "أبها",
        "id": "36",
        "photo": atodg,
        "spillyway_h": 227,
      },
      {
        "north": "18.280428",
        "east": "42.864847",
        "date": "1406هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 3000000,
        "high": 7,
        "length": 10,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "عقده",
        "governorate": "خميس مشيط",
        "id": "37",
        "photo": agda,
        "spillyway_h": 220,
      },
      {
        "north": "19.245278",
        "east": "43.138611",
        "date": "1440هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 639068,
        "high": 5.5,
        "length": 8.5,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "الثفن",
        "governorate": "خميس مشيط",
        "id": "38",
        "photo": althfn,
        "spillyway_h": 189,
      },
      {
        "north": "18.110833",
        "east": "43.142778",
        "date": "1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 26105,
        "high": 4.5,
        "length": 7.5,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "القريحاء",
        "governorate": "سراة عبيده",
        "id": "39",
        "photo": griha,
        "spillyway_h": 186.5,
      },
      {
        "north": "17.981392",
        "east": "43.20996",
        "date": "1424",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 90000,
        "high": 5.5,
        "length": 8,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الرميد",
        "governorate": "سراة عبيده",
        "id": "40",
        "photo": alramid ,
        "spillyway_h": 105,
      },
      {
        "north": "17.941944",
        "east": "43.225833",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 100000,
        "high": 7,
        "length": 10,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "زهره بني بشر",
        "governorate": "سراة عبيده",
        "id": "41",
        "photo": zhra,
        "spillyway_h": 175,
      },
      {
        "north": "18.153911",
        "east": "43.1882",
        "date": "1424",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 108000,
        "high": 9,
        "length": 12,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "خضار",
        "governorate": "سراة عبيده",
        "id": "42",
        "photo": khader,
        "spillyway_h": 241,
      },
      {
        "north": "18.076667",
        "east": "43.235556",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 110000,
        "high": 13,
        "length": 16,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "العمل )زهير(",
        "governorate": "سراة عبيده",
        "id": "43",
        "photo": alamal,
        "spillyway_h": 81,
      },
      {
        "north": "18.035556",
        "east": "43.188611",
        "date": "1432",
        "Sirens": 0,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 47700,
        "high": 3,
        "length": 6,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "ال بسام",
        "governorate": "سراة عبيده",
        "id": "44",
        "photo": bsam,
        "spillyway_h": 176,
      },
      {
        "north": "18.1383",
        "east": "43.134147",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 111170,
        "high": 6,
        "length": 9,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "المشرب",
        "governorate": "سراة عبيده",
        "id": "45",
        "photo": almshreb,
        "spillyway_h": 391,
      },
      {
        "north": "18.014143",
        "east": "43.328845",
        "date": "هـ1425",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 100000,
        "high": 4.25,
        "length": 6,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الوقيره",
        "governorate": "ظهران الجنوب",
        "id": "46",
        "photo": wgier,
        "spillyway_h": 105,
      },
      {
        "north": "17.932042",
        "east": "43.286525",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 79229,
        "high": 9,
        "length": 12,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "محالة عرعرة",
        "governorate": "ظهران الجنوب",
        "id": "47",
        "photo": arara,
        "spillyway_h": 113,
      },
      {
        "north": "17.993643",
        "east": "43.264752",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 86700,
        "high": 12,
        "length": 15,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "ال درهم",
        "governorate": "ظهران الجنوب",
        "id": "48",
        "photo": derham,
        "spillyway_h": 168,
      },
      {
        "north": "18.055833",
        "east": "42.951492",
        "date": "هـ1425",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 1,
        "capacity": 150000,
        "high": 11.5,
        "length": 14,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الغيالن",
        "governorate": "احد رفيده",
        "id": "49",
        "photo": "",
        "spillyway_h": 150,
      },
      {
        "north": "18.050833",
        "east": "42.814444",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 1,
        "capacity": 160000,
        "high": 6.5,
        "length": 9.5,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "ال حديله",
        "governorate": "احد رفيده",
        "id": "50",
        "photo": hdila,
        "spillyway_h": 265,
      },
      {
        "north": "18.0225",
        "east": "43.28201",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 102700,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الفقاعيس",
        "governorate": "سراة عبيده",
        "id": "51",
        "photo": fgais,
        "spillyway_h": 105,
      },
      {
        "north": "17.790833",
        "east": "43.417222",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 0,
        "capacity": 74700,
        "high": 11,
        "length": 14,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "ال عيفه",
        "governorate": "ظهران الجنوب",
        "id": "52",
        "photo": "",
        "spillyway_h": 115,
      },
      {
        "north": "17.634683",
        "east": "43.525867",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 260000,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "القبضه",
        "governorate": "ظهران الجنوب",
        "id": "53",
        "photo": gbda,
        "spillyway_h": 50,
      },
      {
        "north": "17.915733",
        "east": "43.332072",
        "date": "1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 280000,
        "high": 8,
        "length": 11.5,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "الحرجه",
        "governorate": "الحرجة",
        "id": "54",
        "photo": hrga,
        "spillyway_h": 160,
      },
      {
        "north": "18.073139",
        "east": "42.829531",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 1,
        "capacity": 90375,
        "high": 6,
        "length": 9,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الصمخية",
        "governorate": "احد رفيده",
        "id": "55",
        "photo": smakia,
        "spillyway_h": 264,
      },
      {
        "north": "18.162483",
        "east": "42.797581",
        "date": "هـ1403",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 300000,
        "high": 8,
        "length": 11,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "المراغه",
        "governorate": "احد رفيده",
        "id": "56",
        "photo": mrga,
        "spillyway_h": 233,
      },
      {
        "north": "18.283333",
        "east": "43.29365",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 350000,
        "high": 7,
        "length": 10,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "هجرة زهير",
        "governorate": "سراة عبيده",
        "id": "57",
        "photo": hjrzher,
        "spillyway_h": 100,
      },
      {
        "north": "17.993107",
        "east": "43.202364",
        "date": "هـ1423",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 350000,
        "high": 10,
        "length": 13,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "النحره",
        "governorate": "سراة عبيده",
        "id": "58",
        "photo": nhra,
        "spillyway_h": 95,
      },
      {
        "north": "18.212241",
        "east": "43.168404",
        "date": "هـ1429",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 400000,
        "high": 10,
        "length": 13,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "جوف المعمر",
        "governorate": "سراة عبيده",
        "id": "60",
        "photo": gofmamer,
        "spillyway_h": 270,
      },
      {
        "north": "17.958567",
        "east": "43.264369",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 480000,
        "high": 8,
        "length": 11,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "العاديه",
        "governorate": "ظهران الجنوب",
        "id": "61",
        "photo": normal,
        "spillyway_h": 170,
      },
      {
        "north": "18.25985",
        "east": "43.2309",
        "date": "1419",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 500000,
        "high": 8.5,
        "length": 11,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "الرشيد",
        "governorate": "سراة عبيده",
        "id": "62",
        "photo": rshed,
        "spillyway_h": 149,
      },
      {
        "north": "17.758889",
        "east": "43.470278",
        "date": "هـ1430",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 500000,
        "high": 7,
        "length": 10,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "الثابت",
        "governorate": "ظهران الجنوب",
        "id": "63",
        "photo": "",
        "spillyway_h": 120,
      },
      {
        "north": "18.132222",
        "east": "43.0025",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 342926,
        "high": 9,
        "length": 12,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الهجلة",
        "governorate": "احد رفيده",
        "id": "64",
        "photo": hgla1,
        "spillyway_h": 129,
      },
      {
        "north": "17.783333",
        "east": "43.508056",
        "date": "هـ1428",
        "Sirens": 1,
        "Portals": 1,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 0,
        "i_security": 1,
        "capacity": 748000,
        "high": 7,
        "length": 9,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "افياض الطلحه",
        "governorate": "ظهران الجنوب",
        "id": "65",
        "photo": fitlha,
        "spillyway_h": 400,
      },
      {
        "north": "17.881967",
        "east": "43.350467",
        "date": "1403",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 790000,
        "high": 9,
        "length": 12,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "شراقب",
        "governorate": "ظهران الجنوب",
        "id": "66",
        "photo": shergeb,
        "spillyway_h": 70,
      },
      {
        "north": "17.903486",
        "east": "43.470911",
        "date": "هـ1399",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 1000000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "سروم الحرجه",
        "governorate": "ظهران الجنوب",
        "id": "67",
        "photo": shrom,
        "spillyway_h": 75,
      },
      {
        "north": "18.04985",
        "east": "43.227133",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 2000000,
        "high": 18,
        "length": 21,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "عنم",
        "governorate": "سراة عبيده",
        "id": "68",
        "photo": ananm,
        "spillyway_h": 120,
      },
      {
        "north": "17.677728",
        "east": "43.346587",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 211400,
        "high": 16,
        "length": 19,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الغائل",
        "governorate": "ظهران الجنوب",
        "id": "69",
        "photo": gaeel,
        "spillyway_h": 68,
      },
      {
        "north": "17.786944",
        "east": "43.379167",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 71900,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الدافعه",
        "governorate": "ظهران الجنوب",
        "id": "70",
        "photo": "",
        "spillyway_h": 43,
      },
      {
        "north": "17.999178",
        "east": "43.428686",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 2500000,
        "high": 20,
        "length": 23,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الفيض",
        "governorate": "ظهران الجنوب",
        "id": "71",
        "photo": feed,
        "spillyway_h": 130,
      },
      {
        "north": "17.994082",
        "east": "43.114552",
        "date": "هـ1434",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 780000,
        "high": 13,
        "length": 17,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "قرضان",
        "governorate": "سراة عبيده",
        "id": "72",
        "photo": frdan,
        "spillyway_h": 195,
      },
      {
        "north": "18.050278",
        "east": "43.129253",
        "date": "هـ1403",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 55000,
        "high": 3,
        "length": 5,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "السروى",
        "governorate": "سراة عبيده",
        "id": "73",
        "photo": saroi,
        "spillyway_h": 120,
      },
      {
        "north": "18.034772",
        "east": "43.0665",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 60000,
        "high": 8,
        "length": 10.5,
        "type": "ركامي",
        "purpose": "حماية",
        "d_name": "العسران",
        "governorate": "سراة عبيده",
        "id": "74",
        "photo": osran,
        "spillyway_h": 200,
      },
      {
        "north": "18.20185",
        "east": "42.85783",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 100000,
        "high": 2.1,
        "length": 5,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "ابوخضاعه",
        "governorate": "احد رفيده",
        "id": "75",
        "photo": abugadaa,
        "spillyway_h": 65,
      },
      {
        "north": "17.5875",
        "east": "43.541667",
        "date": "1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 519500,
        "high": 13,
        "length": 16,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "كتام",
        "governorate": "ظهران الجنوب",
        "id": "76",
        "photo": ktam,
        "spillyway_h": 166,
      },
      {
        "north": "17.967733",
        "east": "43.196678",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 150000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "العيزاء",
        "governorate": "سراة عبيده",
        "id": "77",
        "photo": alaiza,
        "spillyway_h": 80,
      },
      {
        "north": "17.722339",
        "east": "43.495892",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 107000,
        "high": 14,
        "length": 17,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "ال فروان",
        "governorate": "ظهران الجنوب",
        "id": "78",
        "photo": froon,
        "spillyway_h": 140,
      },
      {
        "north": "18.101472",
        "east": "43.20805",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 250000,
        "high": 7,
        "length": 10,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "وادي داف",
        "governorate": "سراة عبيده",
        "id": "79",
        "photo": wadidaf,
        "spillyway_h": 70,
      },
      {
        "north": "17.914444",
        "east": "43.248889",
        "date": "هـ1419",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 500000,
        "high": 11,
        "length": 14,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "الجوه",
        "governorate": "سراة عبيده",
        "id": "80",
        "photo": algoha,
        "spillyway_h": 122,
      },
      {
        "north": "18.134675",
        "east": "43.105861",
        "date": "هـ1400",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 1500000,
        "high": 18,
        "length": 22,
        "type": "ركامي",
        "purpose": "حماية",
        "d_name": "المحزمه",
        "governorate": "سراة عبيده",
        "id": "81",
        "photo": mohzam,
        "spillyway_h": 280,
      },
      {
        "north": "17.656353",
        "east": "43.462664",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 963000,
        "high": 22,
        "length": 28,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "عراعر",
        "governorate": "ظهران الجنوب",
        "id": "82",
        "photo": araer,
        "spillyway_h": 145,
      },
      {
        "north": "18.024167",
        "east": "43.238889",
        "date": "هـ1441",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 59232,
        "high": 11,
        "length": 14,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "الفرحة",
        "governorate": "سراة عبيده",
        "id": "83",
        "photo": farha,
        "spillyway_h": 57,
      },
      {
        "north": "17.973105",
        "east": "43.393198",
        "date": "هـ1437",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 280000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "شعب الحرجه",
        "governorate": "الحرجة",
        "id": "84",
        "photo": shabhrja,
        "spillyway_h": 62,
      },
  ];
  
  export default Sade;
  