import Wesanb from '../iamge/wesanb.png';
import Radwan from '../iamge/radwan.png';
import Madaa from '../iamge/madaa.png';
import Msireg from '../iamge/msireg.png';
import Oad from '../iamge/oad.png';
import Rada from '../iamge/rada.png';
import Reeima from '../iamge/reeima.png';
import Hswa from '../iamge/hswa.png';
import Bhwan from '../iamge/bhwan.png';
import Reem from '../iamge/reem.png';
import Sharf from '../iamge/sharf.png';
import Roam from '../iamge/roam.png';
import Soda from '../iamge/soda.png';
import Tib from '../iamge/tib.png';
import Btna from '../iamge/btna.png';
import Thoaba from '../iamge/thoaba.png'
import Khdar from '../iamge/khdar.png'
import marba from '../iamge/marba.png'
import ashran from '../iamge/ashran.png'
import tndha from '../iamge/tndha.png'
import anod from '../iamge/anod.png'
import thll from '../iamge/thll.png'






const Sade = [

    {
        "id": "1",
        "photo":Oad,
        "governorate": "رجال المع",
        "d_name": "العوض",
        "purpose ": "حماية",
        "type": "خرساني",
        "length ": "55",
        "high": "12",
        "spillyway_h": "9",
        "capacity": "35.000",
        "i_security": "0",
        "management": "0 ",
        "Guard": " 1",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1406",
        "north": "18.280217",
        "east": "42.33365"
    },
    {
        "id": "2",
        "photo":Reem,
        "governorate": "رجال المع",
        "d_name": "ريم",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "55",
        "high": "11",
        "spillyway_h": "8",
        "capacity": "50.000",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1403",
        "north": "18.235867",
        "east": "42.178497"
    },
    {
        "id": "3",
        "photo":tndha,
        "governorate": "خميس مشيط",
        "d_name": "تندحه",
        "purpose ": "للشرب",
        "type": "خرساني",
        "length ": "120",
        "high": "16",
        "spillyway_h": "10",
        "capacity": "4200.000",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "1",
        "Geotechnical": "0",
        "date": "1402",
        "north": "18.260411",
        "east": "42.715894"
    },
    {
        "id": "4",
        "photo":Soda,
        "governorate": "أبها",
        "d_name": "السودة",
        "purpose ": "حماية",
        "type": "خرساني",
        "length ": "28",
        "high": "13",
        "spillyway_h": "10",
        "capacity": "340.000",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1404",
        "north": "18.29138",
        "east": "42.412778"
    },
    {
        "id": "5",
        "photo":Thoaba,
        "governorate": "رجال المع",
        "d_name": "ثعابه",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "100",
        "high": "11",
        "spillyway_h": "8",
        "capacity": "230.000",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "0",
        "Portals": "1",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1404",
        "north": "18.266239",
        "east": "42.270122"
    },
    {
        "id": "6",
        "photo":Btna,
        "governorate": "خميس مشيط",
        "d_name": "البطنه",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "360",
        "high": "13",
        "spillyway_h": "10",
        "capacity": "151.800",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1404",
        "north": "18.858056",
        "east": "42.655278"
    },
    {
        "id": "7",
        "photo":Roam,
        "governorate": "رجال المع",
        "d_name": "روام",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "57",
        "high": "16",
        "spillyway_h": "13",
        "capacity": "1500.000",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "0",
        "Portals": "1",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1406",
        "north": "18.329722",
        "east": "42.0925"
    },
    {
        "id": "8",
        "photo":Reeima,
        "governorate": "أبها",
        "d_name": "ريمه",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "205",
        "high": "15",
        "spillyway_h": "12",
        "capacity": "230.000",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "1",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1431",
        "north": "18.355",
        "east": "42.386389"
    },
    {
        "id": "9",
        "photo":Sharf,
        "governorate": "أبها",
        "d_name": "طليحة الشرف",
        "purpose ": "استعاضة",
        "type": "ترابي",
        "length ": "281",
        "high": "8",
        "spillyway_h": "6",
        "capacity": "355.650",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1432",
        "north": "18.447222",
        "east": "43.371389"
    },
    {
        "id": "10",
        "photo": Wesanb,
        "governorate": "رجال المع",
        "d_name": "وسانب",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "100",
        "high": "23",
        "spillyway_h": "20",
        "capacity": "182.000",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "0",
        "Portals": "1",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1406",
        "north": "18.358056",
        "east": "42.240833"
    },
    {
        "id": "11",
        "photo":Rada,
        "governorate": "رجال المع",
        "d_name": "راده",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "70",
        "high": "18",
        "spillyway_h": "15",
        "capacity": "192.000",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1406",
        "north": "18.236714",
        "east": "42.205464"
    },
    {
        "id": "12",
        "photo":anod,
        "governorate": "ابها ",
        "d_name": " عنود الجوفي",
        "purpose ": "للشرب",
        "type": "جوفي",
        "length ": "456",
        "high": "28",
        "spillyway_h": "0",
        "capacity": "7000.000",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1428",
        "north": "17.850739",
        "east": "42.386114"
    },
    {
        "id": "13",
        "photo":Radwan,
        
        "governorate": "خميس مشيط",
        "d_name": "روضان",
        "purpose ": "استعاضة",
        "type": "ترابي",
        "length ": "169",
        "high": "6.5",
        "spillyway_h": "4",
        "capacity": "357.160",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1437",
        "north": "18.578056",
        "east": "42.818056"
    },
    {
        "id": "14",
        "photo":thll,
        "governorate": "ابها ",
        "d_name": "تهلل ",
        "purpose ": "استعاضة",
        "type": "ركامي",
        "length ": "140",
        "high": "13.5",
        "spillyway_h": "10.5",
        "capacity": "140.000",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1405",
        "north": "18.403611",
        "east": "42.4"
    },
    {
        "id": "15",
        "photo":ashran,
        "governorate": "أبها",
        "d_name": "عشران",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "111",
        "high": "38",
        "spillyway_h": "31.5",
        "capacity": "1500.000",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "1",
        "Geotechnical": "0",
        "date": "1404",
        "north": "18.269167",
        "east": "42.438056"
    },
    {
        "id": "16",
        "photo":Bhwan,
        "governorate": "أبها",
        "d_name": "بهوان",
        "purpose ": "استعاضة",
        "type": "ترابي",
        "length ": "275",
        "high": "11",
        "spillyway_h": "8",
        "capacity": "121.560",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1432",
        "north": "18.6825",
        "east": "42.413611"
    },
    {
        "id": "17",
        "photo":Tib,
        "governorate": "أبها",
        "d_name": "طيب",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "50",
        "high": "13",
        "spillyway_h": "10",
        "capacity": "90.000",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1403",
        "north": "18.367438",
        "east": "42.361866"
    },
    {
        "id": "18",
        "photo":Msireg,
        "governorate": "خميس مشيط",
        "d_name": "المسيرق",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "84",
        "high": "9",
        "spillyway_h": "6",
        "capacity": "433.000",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1430",
        "north": "19.049444",
        "east": "42.908611"
    },
    {
        "id": "19",
        "photo":Madaa,
        "governorate": "خميس مشيط",
        "d_name": "المضه",
        "purpose ": "استعاضة",
        "type": "ترابي",
        "length ": "1070",
        "high": "8",
        "spillyway_h": "6.5",
        "capacity": "4250.000",
        "i_security": "0",
        "management": "0",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1404",
        "north": "18.787722",
        "east": "43.210619"
    },
    {
        "id": "20",
        "photo":Hswa,
        "governorate": "رجال المع",
        "d_name": "حسوه",
        "purpose ": "استعاضة",
        "type": "خرساني",
        "length ": "11",
        "high": "8",
        "spillyway_h": "200.000",
        "capacity": "0",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "0",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1404",
        "north": "18.204321",
        "east": "42.31512"
    },
    {
        "id": "21",
        "photo":Hswa,
        "governorate": "ابها ",
        "d_name": "ابها",
        "purpose ": "للشرب",
        "type": "خرساني",
        "length ": "350",
        "high": "25.5",
        "spillyway_h": "10.5",
        "capacity": "140.000",
        "i_security": "0",
        "management": "1",
        "Guard": "0",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "1",
        "Sirens": "1",
        "Geotechnical": "1",
        "date": "1404",
        "north": "18.204321",
        "east": "42.31512"
    },
    {
        "id": "22",
        "photo":Khdar,
        "governorate": "خميس مشيط ",
        "d_name": "خضار الحيمة",
        "purpose ": "حماية",
        "type": "ترابي",
        "length ": "648",
        "high": "9",
        "spillyway_h": "6",
        "capacity": "1128.733",
        "i_security": "0",
        "management": "0",
        "Guard": "0",
        "Generator": "0",
        "Lighting ": "1",
        "valves ": "0",
        "Portals": "0",
        "Sirens": "0",
        "Geotechnical": "0",
        "date": "1404",
        "north": "18.204321",
        "east": "42.31512"
    },
    {
        "id": "23",
        "photo":marba,
        "governorate": "مربة  ",
        "d_name": "مرية ",
        "purpose ": "للشرب",
        "type": "ترابي",
        "length ": "215",
        "high": "32",
        "spillyway_h": "26",
        "capacity": "10000.000",
        "i_security": "1",
        "management": "1",
        "Guard": "1",
        "Generator": "1",
        "Lighting ": "1",
        "valves ": "1",
        "Portals": "0",
        "Sirens": "1",
        "Geotechnical": "1",
        "date": "1404",
        "north": "17.903333",
        "east": "42.384722"
    },

   
   ];
   export default Sade;

